import csv
import numpy as np


SOIL_NAMES = {

    "phh2o": "Soil pH",

    "soc": "Organic Carbon",

    "nitrogen": "Nitrogen",

    "clay": "Clay",

    "sand": "Sand",

    "silt": "Silt",

    "bdod": "Bulk Density",

    "cec": "Cation Exchange Capacity"

}

SOIL_CONVERSIONS = {
    "phh2o": 0.1,
    "soc": 0.1,
    "nitrogen": 0.01,
    "clay": 0.1,
    "sand": 0.1,
    "silt": 0.1,
    "bdod": 0.01,
    "cec": 0.1
}

def generate_soil_statistics(layers, output_folder):

    print("\nCalculating Soil Statistics...\n")

    csv_file = output_folder / "SoilStatistics.csv"

    report_file = output_folder / "Soil_Report.txt"

    statistics = []

    with open(csv_file, "w", newline="") as csv_out:

        writer = csv.writer(csv_out)

        units = {
            "phh2o": "pH",
            "soc": "g/kg",
            "nitrogen": "g/kg",
            "clay": "%",
            "sand": "%",
            "silt": "%",
            "bdod": "kg/dm³",
            "cec": "cmol(c)/kg"
        }
       

        
        writer.writerow([
            "Layer",
            "Unit",
            "Minimum",
            "Maximum",
            "Mean",
            "Median",
            "Std Dev"
        ])

        for layer_name, info in layers.items():

            data = info["data"]

            valid = data[np.isfinite(data)]

            if valid.size == 0:

                continue

            conversion = SOIL_CONVERSIONS.get(layer_name, 1.0)

            minimum = float(np.min(valid)) * conversion

            maximum = float(np.max(valid)) * conversion

            mean = float(np.mean(valid)) * conversion

            median = float(np.median(valid)) * conversion

            std = float(np.std(valid)) * conversion

            writer.writerow([

    SOIL_NAMES.get(layer_name, layer_name),

            units.get(layer_name, ""),

            round(minimum, 4),

            round(maximum, 4),

            round(mean, 4),

            round(median, 4),

            round(std, 4)

        ])

            statistics.append({

                "layer": SOIL_NAMES.get(layer_name, layer_name),

                "unit": units.get(layer_name, ""),
                
                "minimum": minimum,

                "maximum": maximum,

                "mean": mean,

                "median": median,

                "std": std

            })

            print(
                f"{SOIL_NAMES.get(layer_name, layer_name)} "
                f"Mean : {mean:.3f}"
            )

    with open(report_file, "w") as report:

        report.write("SOIL ANALYSIS REPORT\n")

        report.write("==============================\n\n")

        for item in statistics:

            report.write(
                f"{item['layer']}\n"
            )

            report.write(
                f"Unit    : {item['unit']}\n"
            )

            report.write(
                f"Minimum : {item['minimum']:.3f}\n"
            )

            report.write(
                f"Maximum : {item['maximum']:.3f}\n"
            )

            report.write(
                f"Mean    : {item['mean']:.3f}\n"
            )

            report.write(
                f"Median  : {item['median']:.3f}\n"
            )

            report.write(
                f"Std Dev : {item['std']:.3f}\n"
            )

            report.write(
                "---------------------------------\n"
            )

        report.write("\nGENERAL INTERPRETATION\n")
        report.write("==============================\n\n")

        ph = next(
            (x["mean"] for x in statistics if x["layer"] == "Soil pH"),
            None
        )

        if ph is not None:

            if ph < 5.5:

                report.write("Soil is strongly acidic.\n")

            elif ph < 6.5:

                report.write("Soil is slightly acidic.\n")

            elif ph <= 7.5:

                report.write("Soil is neutral.\n")

            elif ph <= 8.5:

                report.write("Soil is slightly alkaline.\n")

            else:

                report.write("Soil is highly alkaline.\n")

        report.write("\nModule generated by LARA Soil Analysis\n")

    print("\nCSV Saved")

    print("Report Saved")

    print("\n========== SOIL SUMMARY ==========")

    for item in statistics:

        print(
            f"{item['layer']} : {item['mean']:.3f}"
        )

    print("\nSoil Statistics Completed Successfully.")
