import csv
import numpy as np


def generate_flood_statistics(flood_data, output_folder):

    print("\nCalculating Flood Statistics...\n")

    score = flood_data["score"]

    classes = flood_data["class"]

    rainfall = flood_data["annual_rainfall"]

    valid = score[np.isfinite(score)]

    minimum = float(np.min(valid))
    maximum = float(np.max(valid))
    mean = float(np.mean(valid))
    median = float(np.median(valid))
    std = float(np.std(valid))

    total_pixels = classes.size

    class_names = {
        1: "Very Low",
        2: "Low",
        3: "Moderate",
        4: "High",
        5: "Very High"
    }

    csv_file = output_folder / "FloodStatistics.csv"

    with open(csv_file, "w", newline="") as csvfile:

        writer = csv.writer(csvfile)

        writer.writerow([
            "Risk Class",
            "Pixels",
            "Percentage"
        ])

        for i in range(1, 6):

            pixels = int(np.sum(classes == i))

            percentage = (pixels / total_pixels) * 100

            writer.writerow([
                class_names[i],
                pixels,
                round(percentage, 2)
            ])

    report = output_folder / "Flood_Report.txt"

    with open(report, "w") as f:

        f.write("FLOOD RISK ANALYSIS REPORT\n")
        f.write("====================================\n\n")

        f.write(f"Annual Rainfall : {rainfall:.2f} mm\n")
        f.write(f"Minimum Score   : {minimum:.2f}\n")
        f.write(f"Maximum Score   : {maximum:.2f}\n")
        f.write(f"Average Score   : {mean:.2f}\n")
        f.write(f"Median Score    : {median:.2f}\n")
        f.write(f"Std Deviation   : {std:.2f}\n\n")

        f.write("Risk Distribution\n")
        f.write("------------------------------------\n")

        for i in range(1, 6):

            pixels = int(np.sum(classes == i))

            percentage = (pixels / total_pixels) * 100

            f.write(
                f"{class_names[i]:<12} : "
                f"{pixels:>6} pixels "
                f"({percentage:.2f}%)\n"
            )

        f.write("\nInterpretation\n")
        f.write("------------------------------------\n")

        if mean < 20:
            f.write("Overall flood susceptibility is Very Low.\n")

        elif mean < 40:
            f.write("Overall flood susceptibility is Low.\n")

        elif mean < 60:
            f.write("Overall flood susceptibility is Moderate.\n")

        elif mean < 80:
            f.write("Overall flood susceptibility is High.\n")

        else:
            f.write("Overall flood susceptibility is Very High.\n")

        f.write("\nRecommendations\n")
        f.write("------------------------------------\n")

        if np.sum(classes >= 4) > 0:
            f.write("- Improve drLARAge infrastructure.\n")
            f.write("- Avoid construction in high-risk areas.\n")
            f.write("- Develop flood warning systems.\n")
            f.write("- Promote rainwater harvesting.\n")
        else:
            f.write("- Continue monitoring seasonal rainfall.\n")
            f.write("- Maintain natural drLARAge channels.\n")

        f.write("\nGenerated by LARA Flood Module\n")

    print("Statistics CSV Saved")

    print("Flood Report Saved")

    print("\n========== FLOOD SUMMARY ==========")

    print(f"Minimum Score : {minimum:.2f}")

    print(f"Maximum Score : {maximum:.2f}")

    print(f"Average Score : {mean:.2f}")

    print(f"Median Score  : {median:.2f}")

    print(f"Annual Rainfall : {rainfall:.2f} mm")

    print("\nRisk Distribution")

    for i in range(1, 6):

        pixels = int(np.sum(classes == i))

        percentage = (pixels / total_pixels) * 100

        print(
            f"{class_names[i]:<12} : {percentage:.2f}%"
        )

    print("\nFlood Statistics Completed Successfully.")
